name: Android APK Build

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Install Buildozer and Android SDK
      run: |
        sudo apt update
        sudo apt install -y python3-pip unzip zlib1g-dev wget
        pip install --upgrade pip setuptools
        pip install cython==0.29.19
        pip install buildozer

        # Install Android SDK
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        cd $HOME/Android/Sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        rm cmdline-tools.zip

        # Move the extracted folder into the correct location
        mv cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
        
        # Set Android SDK paths
        export ANDROID_SDK_ROOT=$HOME/Android/Sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH
        
        # Accept licenses and install SDK tools
        yes | sdkmanager --licenses
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --install "build-tools;35.0.0" "platform-tools" "platforms;android-30"

    - name: Install dependencies from requirements.txt
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build APK
      run: |
        buildozer android debug
        mkdir -p output_apk
        cp bin/*.apk output_apk/

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3  # Updated to v3 to fix deprecation issue
      with:
        name: vedicware-apk
        path: output_apk/
